config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show create new destroy] do
      resources :comments, only: %i[create new destroy]
      resources :likes, only: %i[create new] do
        collection do
          get :create
        end
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [] do
        resources :posts, only: %i[index show create] do
          resources :comments, only: %i[index create]
        end
      end
    end
  end



end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all

    return unless user.present?

    can :manage, User, id: user.id
    can :manage, Post, author_id: user.id
    can :manage, Comment, author_id: user.id
    can :create, Like

    return unless user.role == 'admin'

    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'

  after_save :update_comment_counter
  after_destroy :update_comment_counter

  private

  def update_comment_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'

  after_save :update_like_counter
  after_destroy :update_like_counter

  private

  def update_like_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, foreign_key: 'post_id'
  has_many :likes, foreign_key: 'post_id'

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0 }

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  after_create :update_post_counter
  after_destroy :update_post_counter

  private

  def update_post_counter
    user.update(posts_counter: user.posts.count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  after_initialize :set_default_posts_counter, if: :new_record?
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id

  validates :name, presence: true
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  private

  def set_default_posts_counter
    self.posts_counter ||= 0
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  skip_before_action :verify_authenticity_token
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    render json: @comments
    @comment.user = current_user

    if @comment.save
      render json: @comment, status: :created
    else
      render json: { error: 'Failed to create comment' }, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
    render json: @posts
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find_by(id: params[:id])
    return unless @post.nil?

    render json: @post
  end

  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.build(post_params)
    @post.comments_counter = 0
    @post.likes_counter = 0
    if @post.save
      render json: @post, status: :created
    else
      render json: { error: @post.errors.full_messages.to_sentence }, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :photo, :bio, :posts_counter, :email, :password, :password_confirmation, :role)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :photo, :bio, :email, :password, :password_confirmation, :current_password, :role)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to user_post_path(@post.user, @post)
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = post.comments.find_by(id: params[:id])
    @comment.destroy
    redirect_back_or_to root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = @post.likes.build(user: current_user)

    if @like.save
      redirect_to user_post_path(@post.user, @post)
    else
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @user = User.find(params[:user_id])
    per_page = 2
    page = params[:page].to_i.positive? ? params[:page].to_i : 1
    offset = (page - 1) * per_page

    @posts = @user.posts.order(created_at: :desc).limit(per_page).offset([offset, 0].max)

    if @posts.empty?
      flash.now[:notice] = 'This user has no posts.'
    else
      @recent_comments = Comment.where(post_id: @posts)
        .includes(:user)
        .select('DISTINCT ON (post_id) *')
    end
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find_by(id: params[:id])
    return unless @post.nil?

    redirect_to user_posts_path(@user)
  end

  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.build(post_params)
    @post.comments_counter = 0
    @post.likes_counter = 0
    if @post.save
      redirect_to user_post_path(@user, @post)
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = @user.posts.find_by(id: params[:id])
    @post.destroy

    redirect_to user_path(@user)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: %i[index show]

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
    return unless @user.nil?

    redirect_to users_path
  end

  private

  def load_and_authorize_user
    @user = User.find(params[:id])
    authorize! :read, @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/index.html.erb
<div class="flex flex-col items-center justify-center gap-8 pb-20">
    <%= render partial: "users/user", locals: {person: @user} %>
     <div class="posts-container">
        <% @user.posts.each do |post| %>
            <%= render partial: "users/posts", locals: {post: post} %>
            <div class=" bg-blue-100 p-4 rounded-md -mt-2 flex flex-col gap-2">
                <%  comments = post.recent_comments%>
                <% comments.each do |comment| %>
                    <p class="italic p-2 bg-slate-50 rounded-md">
                      <span class="text-red-300 font-medium"><%= comment.user.name%></span>:&nbsp;
                      <%= comment.text%> 
                    </p>
                <% end %>
            </div>
        <% end %>
    </div> 

    <div class="flex flex-col gap-4 w-[500px] bg-blue-100 rounded-md p-8">
      <%= form_for([@user, @user.posts.build]) do |f| %>
        <div class="flex flex-col">
          <%= f.label :title, class: "text-lg font-medium mb-2" %>
          <%= f.text_field :title, class: "border border-gray-300 px-3 py-2 rounded" %>
        </div>
        <div class="flex flex-col mt-2">
          <%= f.label :text, class: "text-lg font-medium mb-2" %>
          <%= f.text_area :text, class: "border border-gray-300 px-3 py-2 rounded" %>
        </div>
        <div class="flex justify-center mt-4">
          <%= f.submit "Create Post", class: "bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600" %>
        </div>
      <% end %>
    </div>

</div>

app/views/posts/new.html.erb
<div class="flex flex-col gap-4 w-[500px] bg-blue-100 rounded-md p-8">
      <%= form_for([@user, @user.posts.build]) do |f| %>
        <div class="flex flex-col">
          <%= f.label :title, class: "text-lg font-medium mb-2" %>
          <%= f.text_field :title, class: "border border-gray-300 px-3 py-2 rounded" %>
        </div>
        <div class="flex flex-col mt-2">
          <%= f.label :text, class: "text-lg font-medium mb-2" %>
          <%= f.text_area :text, class: "border border-gray-300 px-3 py-2 rounded" %>
        </div>
        <div class="flex justify-center mt-4">
          <%= f.submit "Create Post", class: "bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600" %>
        </div>
      <% end %>
    </div>

app/views/posts/show.html.erb
<div class="flex items-center justify-center mt-12 pb-10">
   <div class="p-4 w-[500px] bg-blue-100 cursor-default rounded-md">
      <div class="p-4 bg-slate-100 rounded-md items-center justify-center">
        <div class="flex justify-between items-center">
          <p class="font-medium text-xl"><%= "#{@post.title} by #{@user.name}" %></p>
          <div class="flex gap-2 text-xs">
            <small class="text-sm font-medium">Comments: <%= @post.comments_counter %></small>
            <small class="text-sm font-medium">
              <%= link_to "Likes: #{@post.likes_counter}", user_post_likes_path(@user, @post) %>
            </small>
          </div>
        </div>
  
        <p class="mt-4 italic text-sm"><%= @post.text%></p>   
        <% if can?(:destroy, @post) %>
          <%= link_to 'Delete', user_post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
      </div>
      <div class="flex flex-col mt-2">
        <% @post.comments.each do |comment| %>
          <p class="italic p-2 bg-slate-50">
            <span class="text-red-300 font-medium"><%= comment.user.name%></span>:&nbsp;
            <%= comment.text%> 
          </p>
           <% if can?(:destroy, comment) %>
          <%= link_to 'Delete', user_post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
        <% end %>
  </div>

  <div class="flex flex-col gap-4 bg-blue-100 rounded-md p-8">
    <%= form_for([@user, @post, @post.comments.build]) do |f| %>
      <div class="flex flex-col">
        <%= f.label :text, class: "text-lg font-medium mb-2" %>
        <%= f.text_area :text, class: "border border-gray-300 px-3 py-2 rounded" %>
      </div>
      <div class="flex justify-center mt-4">
        <%= f.submit "Create Comment", class: "bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600" %>
      </div>
    <% end %>
  </div>


  <div class="mt-12 flex gap-2 items-center justify-center">
    <%= link_to 'Back to All Users', users_path, class: 'p-2 rounded-md bg-blue-400 text-white hover:bg-blue-600' %>
    <%= link_to 'Back to User Posts', user_posts_path(@user), class: 'p-2 rounded-md bg-blue-400 text-white hover:bg-blue-600' %>
  </div>
</div>

app/views/users/_posts.html.erb
<div class="flex flex-col justify-between p-4 w-[500px] bg-blue-100 cursor-default rounded-md">
    <div class="p-2 bg-slate-100 rounded-md">
      <%= link_to post.title, user_post_path(@user, post) %> 
      <p class="mt-4 italic text-sm"><%= truncate(post.text, length: 100, omission: '...' ) %>
          
      <div class="flex gap-2 ml-[60%] mt-8">
        <small class="text-sm font-medium">
          <%= link_to "Comments: #{post.comments_counter}", user_post_path(@user, post) %>
        </small>
        <small class="text-sm font-medium">
          <%= link_to "Likes: #{post.likes_counter}", user_post_likes_path(@user, post)%>
        </small>
      </div>
    </div>
</div> 

app/views/users/_user.html.erb
<div class="flex items-center justify-center">
      <div class="flex items-center justify-center gap-10 mt-8 p-4 bg-blue-100 cursor-pointer rounded-md"
      >  
        <img src="<%= person.photo %>" alt="User Photo" class="h-[120px] w-[120px]"/>
        <div class="flex flex-col h-[120px] w-[300px] justify-between p-4 rounded-md bg-blue-200 border-1 border-black">
          <p class="text-2xl font-medium"><%= person.name %></p>
            <span class="role-badge"><%= person.role || "member" %></span>
          <p class="ml-[50%] text-sm">Number of Posts: <%= person.posts_counter %></p>
        </div>
      </div>
</div>

app/views/users/index.html.erb
<div class="flex flex-col gap-2 items-center justify-center mt-12">
  <% @users.each do |person| %>
    <a href="<%= user_path(person) %>">
      <div class="flex items-center justify-center gap-10 mt-8 p-4 bg-blue-100 hover:bg-blue-400 cursor-pointer rounded-md
        transform hover:scale-110 transition-all duration-300 active:scale-90"
      >  
        <img src="<%= person.photo %>" alt="User Photo" class="h-[120px] w-[120px]"/>
        <div class="flex flex-col h-[120px] w-[300px] justify-between p-4 rounded-md bg-blue-200 border-1 border-black">
          <p class="text-2xl font-medium"><%= person.name %></p>
            <span class="role-badge"><%= person.role || "member" %></span>
          <p class="ml-[50%] text-sm">Number of Posts: <%= person.posts_counter %></p>
        </div>
      </div>
    </a>
  <% end %>
  <%= link_to "Sign out", destroy_user_session_path, method: :get , class: "sign-up login"%>
</div>

app/views/users/show.html.erb
<div class="flex flex-col items-center justify-center gap-8">
  <%= render partial: "user", locals: {person: @user} %>
  <%posts = @user.recent_posts%>
  <div class="flex flex-col justify-between p-4 w-[500px] bg-blue-100 cursor-default rounded-md">
    <p class="font-medium text-xl">Bio:</p>
    <p class="mt-4 italic text-sm"><%= @user.bio %></p>
  </div>
  
  <% posts.each do |post| %>
    <%= render partial: "posts", locals: {post: post} %>
  <% end %>
  
  <button class="p-2 rounded-md bg-blue-500 text-white hover:bg-blue-700 transform hover:scale-110 transition-all duration-300 active:scale-90">
    <%= link_to 'Show All Posts', user_posts_path(@user) %>
  </button>
</div>